export const USER = {
  REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  LOGOUT: 'USER_LOGOUT',

  GET_TOKEN: 'USER_GET_TOKEN',
  SAVE_TOKEN: 'USER_SAVE_TOKEN',
  REFRESH_TOKEN: 'USER_REFRESH_TOKEN',
  REMOVE_TOKEN: 'USER_REMOVE_TOKEN',

  LOADING: 'USER_LOADING',
  ERROR: 'USER_ERROR',
  
  GET_ALL_REQUEST: 'USER_GET_ALL_REQUEST',
  GET_ALL_SUCCESS: 'USER_GET_ALL_SUCCESS',
  GET_ALL_FAILURE: 'USER_GET_ALL_FAILURE',

  GET_DASHBOARD_REQUEST: 'USER_GET_DASHBOARD_REQUEST',
  GET_DASHBOARD_SUCCESS: 'USER_GET_DASHBOARD_SUCCESS',
  GET_DASHBOARD_FAILURE: 'USER_GET_DASHBOARD_FAILURE',

  GET_RESERVATION_REQUEST: 'USER_GET_RESERVATION_REQUEST',
  GET_RESERVATION_SUCCESS: 'USER_GET_RESERVATION_SUCCESS',
  GET_RESERVATION_FAILURE: 'USER_GET_RESERVATION_FAILURE',

  GET_CHANNEL_STATS_REQUEST: 'USER_GET_CHANNEL_STATS_REQUEST',
  GET_CHANNEL_STATS_SUCCESS: 'USER_GET_CHANNEL_STATS_SUCCESS',
  GET_CHANNEL_STATS_FAILURE: 'USER_GET_CHANNEL_STATS_FAILURE',

  GET_YEAR_STATS_REQUEST: 'USER_GET_YEAR_STATS_REQUEST',
  GET_YEAR_STATS_SUCCESS: 'USER_GET_YEAR_STATS_SUCCESS',
  GET_YEAR_STATS_FAILURE: 'USER_GET_YEAR_STATS_FAILURE',

  GET_COMPARISON_REQUEST: 'USER_GET_COMPARISON_REQUEST',
  GET_COMPARISON_SUCCESS: 'USER_GET_COMPARISON_SUCCESS',
  GET_COMPARISON_FAILURE: 'USER_GET_COMPARISON_FAILURE',

  DELETE_REQUEST: 'USER_DELETE_REQUEST',
  DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
  DELETE_FAILURE: 'USER_DELETE_FAILURE',
};