const AUTH = {
  APP_TOKEN_REQUEST: 'AUTH_APP_TOKEN_REQUEST',
  APP_TOKEN_SUCCESS: 'AUTH_APP_TOKEN_SUCCESS',
  APP_TOKEN_FAILURE: 'AUTH_APP_TOKEN_FAILURE',

  LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',

  LOGOUT_REQUEST: 'AUTH_LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'AUTH_LOGOUT_FAILURE',
};

export default AUTH;
