// AUTHENTICATION case types
export default AUTH = {
  APP_TOKEN_REQUEST: 'APP_TOKEN_REQUEST',
  APP_TOKEN_SUCCESS: 'AUTH_APP_TOKEN_SUCCESS',
  APP_TOKEN_FAILURE: 'AUTH_APP_TOKEN_FAILURE',

  LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',

  LOGOUT_REQUEST: 'AUTH_LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'AUTH_LOGOUT_FAILURE',

  // REGISTER_REQUEST: 'AUTH_REGISTER_REQUEST',
  // REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  // REGISTER_FAILURE: 'AUTH_REGISTER_FAILURE',

  // PASSWORD_RESET_REQUEST: 'AUTH_PASSWORD_RESET_REQUEST',
  // PASSWORD_RESET_SUCCESS: 'AUTH_PASSWORD_RESET_SUCCESS',
  // PASSWORD_RESET_FAILURE: 'AUTH_PASSWORD_RESET_FAILURE',

  // ACCOUNT_DELETE_REQUEST: 'AUTH_ACCOUNT_DELETE_REQUEST',
  // ACCOUNT_DELETE_SUCCESS: 'AUTH_ACCOUNT_DELETE_SUCCESS',
  // ACCOUNT_DELETE_FAILURE: 'AUTH_ACCOUNT_DELETE_FAILURE',
};
