// DASHBOARD case types
const DASHBOARD = {
  DATA_CLEAN_UP: 'DASHBOARD_DATA_CLEAN_UP',
  DATA_REQUEST: 'DASHBOARD_DATA_REQUEST',
  DATA_SUCCESS: 'DASHBOARD_DATA_SUCCESS',
  DATA_FAILURE: 'DASHBOARD_DATA_FAILURE',
};

export default DASHBOARD;
