const DATE = {
  CHOSEN_DATE: 'DATE_CHOSEN_DATE',
  CHOSEN_MONTH: 'DATE_CHOSEN_MONTH',
  CHOSEN_MONTH_RANGE: 'DATE_MONTH_RANGE',
  CHOSEN_YEAR: 'DATE_CHOSEN_YEAR',
  ERROR: 'DATE_ERROR',
};

export default DATE;
