const HOTEL = {
  DATA_REQUEST: 'HOTEL_DATA_REQUEST',
  DATA_SUCCESS: 'HOTEL_DATA_SUCCESS',
  DATA_FAILURE: 'HOTEL_DATA_FAILURE',
  SET_HOTEL_ID: 'HOTEL_SET_HOTEL_ID',
  SET_USER_CHOSEN_HOTEL_ID: 'SET_USER_CHOSEN_HOTEL_ID',
  SET_DEFAULT_HOTEL_ID: 'SET_DEFAULT_HOTEL_ID',
  MODAL_TO_CHOOSE_HOTEL_ID: 'HOTEL_MODAL_TO_CHOOSE_HOTEL_ID',
  CLOSE_MODAL_WITH_HOTEL_ID: 'HOTEL_CLOSE_MODAL_WITH_HOTEL_ID',
  NO_HOTEL_FOUND: 'HOTEL_NO_HOTEL_FOUND',
  PURGE_ALL_DATA: 'HOTEL_PURGE_ALL_DATA',
};

export default HOTEL;
