// HOTEL case types
export default HOTEL = {
  DATA_REQUEST: 'HOTEL_DATA_REQUEST',
  DATA_SUCCESS: 'HOTEL_DATA_SUCCESS',
  DATA_FAILURE: 'HOTEL_DATA_FAILURE',
  SET_HOTEL_ID: 'HOTEL_SET_HOTEL_ID',
  MODAL_TO_CHOOSE_HOTEL_ID: 'HOTEL_MODAL_TO_CHOOSE_HOTEL_ID',
  NO_HOTEL_FOUND: 'HOTEL_NO_HOTEL_FOUND',
};
