// RESERVATION case types
export default RESERVATION = {
  DATA_REQUEST: 'RESERVATION_DATA_REQUEST',
  DATA_SUCCESS: 'RESERVATION_DATA_SUCCESS',
  DATA_FAILURE: 'RESERVATION_DATA_FAILURE',
  // Only for requesting new pages
  NEXT_PAGE_REQUEST: 'RESERVATION_NEXT_PAGE_REQUEST',
  NEXT_PAGE_SUCCESS: 'RESERVATION_NEXT_PAGE_SUCCESS',
  NEXT_PAGE_FAILURE: 'RESERVATION_NEXT_PAGE_FAILURE',
  // Handling last page case
  LAST_PAGE_REACHED: 'RESERVATION_LAST_PAGE_REACHED',
};
