// STATS case types
export default STATS = {
  // Bars tab
  BY_YEAR_DATA_REQUEST: 'STATS_BY_YEAR_DATA_REQUEST',
  BY_YEAR_DATA_SUCCESS: 'STATS_BY_YEAR_DATA_SUCCESS',
  BY_YEAR_DATA_FAILURE: 'STATS_BY_YEAR_DATA_FAILURE',
  // Channel tab
  BY_CATEGORY_DATA_REQUEST: 'STATS_BY_CATEGORY_DATA_REQUEST',
  BY_CATEGORY_DATA_SUCCESS: 'STATS_BY_CATEGORY_DATA_SUCCESS',
  BY_CATEGORY_DATA_FAILURE: 'STATS_BY_CATEGORY_DATA_FAILURE',
};
