// #1 AUTHENTICATION case types
export const AUTH = {
  REGISTER_REQUEST: 'AUTH_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'AUTH_REGISTER_FAILURE',

  LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',

  LOGOUT_REQUEST: 'AUTH_LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'AUTH_LOGOUT_FAILURE',

  PASSWORD_RESET_REQUEST: 'AUTH_PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_SUCCESS: 'AUTH_PASSWORD_RESET_SUCCESS',
  PASSWORD_RESET_FAILURE: 'AUTH_PASSWORD_RESET_FAILURE',

  APP_TOKEN_GET: 'AUTH_APP_TOKEN_GET',
  APP_TOKEN_SAVE: 'AUTH_APP_TOKEN_SAVE',
  APP_TOKEN_REFRESH: 'AUTH_APP_TOKEN_REFRESH',
  APP_TOKEN_REMOVE: 'AUTH_APP_TOKEN_REMOVE',

  USER_TOKEN_GET: 'AUTH_USER_TOKEN_GET',
  USER_TOKEN_SAVE: 'AUTH_USER_TOKEN_SAVE',
  USER_TOKEN_REFRESH: 'AUTH_USER_TOKEN_REFRESH',
  USER_TOKEN_REMOVE: 'AUTH_USER_TOKEN_REMOVE',

  ACCOUNT_DELETE_REQUEST: 'AUTH_ACCOUNT_DELETE_REQUEST',
  ACCOUNT_DELETE_SUCCESS: 'AUTH_ACCOUNT_DELETE_SUCCESS',
  ACCOUNT_DELETE_FAILURE: 'AUTH_ACCOUNT_DELETE_FAILURE',
};

// #2 MEMBERSHIP case types
export const MEMBERSHIP = {
  UPGRADE_REQUEST: 'MEMBERSHIP_UPGRADE_REQUEST',
  UPGRADE_SUCCESS: 'MEMBERSHIP_UPGRADE_SUCCESS',
  UPGRADE_FAILURE: 'MEMBERSHIP_UPGRADE_FAILURE',

  DOWNGRADE_REQUEST: 'MEMBERSHIP_DOWNGRADE_REQUEST',
  DOWNGRADE_SUCCESS: 'MEMBERSHIP_DOWNGRADE_SUCCESS',
  DOWNGRADE_FAILURE: 'MEMBERSHIP_DOWNGRADE_FAILURE',

  CANCEL_REQUEST: 'MEMBERSHIP_CANCEL_REQUEST',
  CANCEL_SUCCESS: 'MEMBERSHIP_CANCEL_SUCCESS',
  CANCEL_FAILURE: 'MEMBERSHIP_CANCEL_FAILURE',
};

// #3 All screens data case types
export const DASHBOARD = {
  GET_REQUEST: 'DASHBOARD_GET_REQUEST',
  GET_SUCCESS: 'DASHBOARD_GET_SUCCESS',
  GET_FAILURE: 'DASHBOARD_GET_FAILURE',
};
export const RESERVATION = {
  GET_REQUEST: 'RESERVATION_GET_REQUEST',
  GET_SUCCESS: 'RESERVATION_GET_SUCCESS',
  GET_FAILURE: 'RESERVATION_GET_FAILURE',
};
export const CHANNEL_STATS = {
  GET_REQUEST: 'CHANNEL_STATS_GET_REQUEST',
  GET_SUCCESS: 'CHANNEL_STATS_GET_SUCCESS',
  GET_FAILURE: 'CHANNEL_STATS_GET_FAILURE',
};
export const YEAR_STATS = {
  GET_REQUEST: 'YEAR_STATS_GET_REQUEST',
  GET_SUCCESS: 'YEAR_STATS_GET_SUCCESS',
  GET_FAILURE: 'YEAR_STATS_GET_FAILURE',
};
export const CHANNEL_STATS = {
  GET_REQUEST: 'CHANNEL_STATS_GET_REQUEST',
  GET_SUCCESS: 'CHANNEL_STATS_GET_SUCCESS',
  GET_FAILURE: 'CHANNEL_STATS_GET_FAILURE',
};
export const COMPARISON = {
  GET_REQUEST: 'COMPARISON_GET_REQUEST',
  GET_SUCCESS: 'COMPARISON_GET_SUCCESS',
  GET_FAILURE: 'COMPARISON_GET_FAILURE',

  DELETE_REQUEST: 'AUTH_DELETE_REQUEST',
  DELETE_SUCCESS: 'AUTH_DELETE_SUCCESS',
  DELETE_FAILURE: 'AUTH_DELETE_FAILURE',
};

// #4 DEVICE state case types
export const DEVICE = {
  LOADING: 'DEVICE_LOADING',
  REFRESHED: 'DEVICE_REFRESHED',
  ERROR: 'DEVICE_ERROR',
  INTERNET_CONNECTED: 'DEVICE_INTERNET_CONNECTED',
  INTERNET_DISCONNECTED: 'DEVICE_INTERNET_DISCONNECTED',
};
