// Theme
import { COLORS, SIZES, POSITIONING, COLOR_PALETTE } from './theme';
// Data types
import {
  RESERVATION_TYPE,
  RESERVATION_TYPE_LABEL,
  RESERVATION_STATUS_LABEL,
  RESERVATION_STATUS,
  ARRIVALS_TYPE,
  GUEST_TYPE,
  SOURCE_NAME,
  SOURCE_TYPE,
  SEGMENT_VALUES,
  RESERVATION_TYPE_CAROUSEL,
  COMPARISON_CARD_VALUES,
  YEARS_ARRAY,
  SETTINGS_MENU_ARRAY,
} from './dataTypes';

export {
  // Theme
  COLORS,
  SIZES,
  POSITIONING,
  COLOR_PALETTE,
  // Data types
  RESERVATION_TYPE,
  RESERVATION_TYPE_LABEL,
  RESERVATION_STATUS_LABEL,
  RESERVATION_STATUS,
  ARRIVALS_TYPE,
  GUEST_TYPE,
  SOURCE_NAME,
  SOURCE_TYPE,
  SEGMENT_VALUES,
  RESERVATION_TYPE_CAROUSEL,
  COMPARISON_CARD_VALUES,
  YEARS_ARRAY,
  SETTINGS_MENU_ARRAY,
};
