import theme, { COLORS, SIZES, FONTS, POSITIONING } from './theme';
import {
  RESERVATION_TYPE,
  RESERVATION_TYPE_LABEL,
  RESERVATION_STATUS_LABEL,
  RESERVATION_STATUS,
  ARRIVALS_TYPE,
  GUEST_TYPE,
  SOURCE_NAME,
  SOURCE_TYPE,
  SEGMENT_VALUES,
  RESERVATION_TYPE_CAROUSEL,
  COMPARISON_CARD_VALUES,
} from './dataTypes';
export {
  theme,
  COLORS,
  SIZES,
  FONTS,
  POSITIONING,
  // DATA types
  RESERVATION_TYPE,
  RESERVATION_TYPE_LABEL,
  RESERVATION_STATUS_LABEL,
  RESERVATION_STATUS,
  ARRIVALS_TYPE,
  GUEST_TYPE,
  SOURCE_NAME,
  SOURCE_TYPE,
  SEGMENT_VALUES,
  RESERVATION_TYPE_CAROUSEL,
  COMPARISON_CARD_VALUES,
};
