// Theme
import { COLORS, SIZES, POSITIONING, COLOR_PALETTE } from './theme';
// Data types
import {
  RESERVATION_TYPE,
  RESERVATION_STATUS,
  SOURCE_NAME,
  SOURCE_TYPE,
  SEGMENT_VALUES,
  ARRIVALS_TYPE,
  COMPARISON_CARD_VALUES,
  YEARS_ARRAY,
  SETTINGS_MENU_ARRAY,
  MONTHS_ARRAY,
  WEEKDAYS_SHORT_ARRAY,
  ITEM_SIZE,
  ITEM_SPACING,
  DAYS_ARRAY,
} from './dataTypes';

export {
  // Theme
  COLORS,
  SIZES,
  POSITIONING,
  COLOR_PALETTE,
  // Data types
  RESERVATION_TYPE,
  RESERVATION_STATUS,
  ARRIVALS_TYPE,
  SOURCE_NAME,
  SOURCE_TYPE,
  SEGMENT_VALUES,
  COMPARISON_CARD_VALUES,
  YEARS_ARRAY,
  SETTINGS_MENU_ARRAY,
  MONTHS_ARRAY,
  WEEKDAYS_SHORT_ARRAY,
  ITEM_SIZE,
  ITEM_SPACING,
  DAYS_ARRAY,
};
