require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'SmartBooking' do
  config = use_native_modules!
  pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false

  )

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'SmartBookingTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  # post_install do |installer|
  #   react_native_post_install(installer)
  #   __apply_Xcode_12_5_M1_post_install_workaround(installer)
  # end

#   use_flipper!({ 'Flipper-Folly' => '2.6.0', 'Flipper' => '0.112.0', 'Flipper-RSocket' => '1.4.0' })

#   post_install do |installer|
#  react_native_post_install(installer)
#  __apply_Xcode_12_5_M1_post_install_workaround(installer)
 
#   flipper_post_install(installer)
 
#   find_and_replace("Pods/Headers/Private/RCT-Folly/folly/synchronization/DistributedMutex-inl.h",
#   "atomic_notify_one(state)", "folly::atomic_notify_one(state)")
 
#   find_and_replace("Pods/Flipper-Folly/folly/synchronization/DistributedMutex-inl.h",
#   "atomic_wait_until(&state, previous | data, deadline)", "folly::atomic_wait_until(&state, previous | data, deadline)")
 
#   end
end
