# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Bug fixes, new features. Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore")
    increment_build_number(xcodeproj: "SmartBooking.xcodeproj")
    build_app(workspace: "SmartBooking.xcworkspace", scheme: "SmartBooking")

  commit_version_bump(
    message: "Deployed new build #{lane_context[SharedValues::BUILD_NUMBER]}",
    xcodeproj: './SmartBooking.xcodeproj'
  )
    upload_to_testflight
    pilot
  end
end
