import { COLOR_PALETTE } from '../../../../../constants/theme';

export const donutConfig = {
  // caption: 'Split of Revenue by Product Categories',
  // subCaption: 'Last year',
  // numberPrefix: 'UZS',
  numberSuffix: ' UZS',
  // defaultCenterLabel: `${defaultDataLabel}: ${defaultDataValue}`,
  centerLabel: '$label: $value',
  centerLabelColor: '#FFFFFF',
  baseFontColor: '#FFFFFF',
  toolTipBgColor: '#212831',
  toolTipBorderColor: '#212831',
  // labelDistance: 20,
  thousandSeparator: '$value',
  plottooltext: '$value UZS',
  decimals: '0',
  theme: 'fusion',
  plotBorderThickness: 5,
  startingAngle: 90,
  animateClockwise: true,
  enableSlicing: 1,
  bgColor: '#212831',
  doughnutRadius: '80%',
  paletteColors: COLOR_PALETTE,
  borderThickness: 20,
  patternAngle: 120,
  enableSmartLabels: 1,
  pieRadius: 60,
  showLabels: 0,
  showValues: 0,
  decimals: 1,
  showLegend: 0,
  legendPosition: 'right',
  legendItemFontSize: 12,
  legendItemFontColor: '#FFFFFF',
  // chartRightMargin: 60,
  // legendItemFont: 'SF Pro Display',
  // interactiveLegend: 1,
  // legendScrollEnabled: 0,
  minimiseWrappingInLegend: 0,
  // showPercentInToolTip: 1,
};
