// #1 AUTHENTICATION case types
export default AUTH = {
  REGISTER_REQUEST: 'AUTH_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'AUTH_REGISTER_FAILURE',

  LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',

  LOGOUT_REQUEST: 'AUTH_LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'AUTH_LOGOUT_FAILURE',

  PASSWORD_RESET_REQUEST: 'AUTH_PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_SUCCESS: 'AUTH_PASSWORD_RESET_SUCCESS',
  PASSWORD_RESET_FAILURE: 'AUTH_PASSWORD_RESET_FAILURE',

  APP_TOKEN_GET: 'AUTH_APP_TOKEN_GET',
  APP_TOKEN_SAVE: 'AUTH_APP_TOKEN_SAVE',
  APP_TOKEN_REFRESH: 'AUTH_APP_TOKEN_REFRESH',
  APP_TOKEN_REMOVE: 'AUTH_APP_TOKEN_REMOVE',

  USER_TOKEN_GET: 'AUTH_USER_TOKEN_GET',
  USER_TOKEN_SAVE: 'AUTH_USER_TOKEN_SAVE',
  USER_TOKEN_REFRESH: 'AUTH_USER_TOKEN_REFRESH',
  USER_TOKEN_REMOVE: 'AUTH_USER_TOKEN_REMOVE',

  ACCOUNT_DELETE_REQUEST: 'AUTH_ACCOUNT_DELETE_REQUEST',
  ACCOUNT_DELETE_SUCCESS: 'AUTH_ACCOUNT_DELETE_SUCCESS',
  ACCOUNT_DELETE_FAILURE: 'AUTH_ACCOUNT_DELETE_FAILURE',
};
